# Change these first
owner: vlfz # Your GitHub organization or username, where this repository lives
repo: uptime.sqdsh.top # The name of this repository

sites:
  - name: BotiCord
    url: https://boticord.top
  - name: BotiCord API [v1]
    url: https://api.boticord.top/v1
  - name: bcord.cc [BotiCord Shorter]
    url: https://bcord.cc
  - name: ENV [Mastodon]
    url: https://env.sqdsh.top
  - name: Sadly Shape Cloud [Gitea]
    url: https://git.sqdsh.top

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.sqdsh.top
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/32297717?v=4
  name: SQDSH Uptime
  introTitle: "Мониторинг работы всех сервисов SQDSH"
  introMessage: Мониторинг работы всех сервисов SQDSH - BotiCord, The Nether и т.д.
  navbar:
    - title: Главная
      href: /
    - title: Основной сайт
      href: https://sqdsh.top
    - title: BotiCord
      href: https://boticord.top

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
